name: Publish NuGet Package

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore --project src/SpringScrap.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore --project src/SpringScrap.csproj

      - name: Pack
        run: dotnet pack --configuration Release --no-restore --output . --project src/SpringScrap.csproj

      - name: Push to NuGet
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate